mysite/mysite/urls.py
from django.contrib import admin
from django.urls import path, include

urlpatterns = [
    path('', include('translate.urls')),
    path('admin/', admin.site.urls),
]

mysite/personal/models.py
from django.db import models

# Create your models here.

mysite/personal/forms.py
from django import forms
from django.contrib.auth import (
    authenticate,
    get_user_model,
    login,
    logout,
)
from django.contrib.auth.forms import UserCreationForm


User = get_user_model()


class UserLoginForm(forms.Form):
    username = forms.CharField()
    password = forms.CharField(widget=forms.PasswordInput)

    def clean(self, *args, **kwargs):
        username = self.cleaned_data.get('username')
        password = self.cleaned_data.get('password')
        #if username and password:
        user = authenticate(username=username, password=password)
        if not user:
            raise forms.ValidationError("This user does not exist")
        if not user.check_password(password):
            raise forms.ValidationError("Incorrect password")
        if not user.is_active:
            raise forms.ValidationError("This user is no longer active")
        return super(UserLoginForm, self).clean(*args, **kwargs)


class UserRegisterForm(forms.ModelForm):
    email = forms.EmailField(label='Email Address')
    email2 = forms.EmailField(label='Confirm Email')
    password = forms.CharField(widget=forms.PasswordInput)

    class Meta:
        model = User
        fields = ['username', 'email', 'email2', 'password']

    def clean_email2(self):
        email = self.cleaned_data.get('email')
        email2 = self.cleaned_data.get('email2')
        if email != email2:
            raise forms.ValidationError('Emails must match!')

        email_qs = User.objects.filter(email=email)
        if email_qs.exists():
            raise forms.ValidationError('This email has already been registered')
        return email


class UserUpdateForm(forms.ModelForm):
    email = forms.EmailField()

    class Meta:
        model = User
        fields = ['email']

mysite/personal/views.py
from django.shortcuts import render, redirect, get_object_or_404
from django.contrib import messages
from django.contrib.auth import (
    authenticate,
    get_user_model,
    login,
    logout,
)
from .forms import (UserLoginForm,
                    UserRegisterForm,
                    UserUpdateForm)
from translate import forms as translate_forms
from translate import models as translate_models


def index(request):
    return render(request, 'personal/index.html')


def user_login(request):
    next = request.GET.get('next')
    form = UserLoginForm(request.POST or None)
    if form.is_valid():
        username = form.cleaned_data.get('username')
        password = form.cleaned_data.get('password')
        user = authenticate(username=username, password=password)
        login(request, user)
        if next:  # This redirects the user from the login page to the page they wanted to visit without being authenticated
            return redirect(next)
        return redirect('contentlist')

    return render(request, 'personal/user_login.html', {'form': form})


def user_register(request):
    form = UserRegisterForm(request.POST or None)
    if form.is_valid():
        user = form.save(commit=False)
        password = form.cleaned_data.get('password')
        user.set_password(password)
        user.save()

        new_user = authenticate(username=user.username, password=password)
        login(request, new_user)
        translate_models.DestinationLanguage.objects.create(
            destLanguage='EN',
            user=request.user
        )
        return redirect('contentlist')

    #context = {"form": form}

    return render(request, 'personal/user_register.html', {"form": form})


def user_profile(request, pk):
    user = request.user
    destLanguage = translate_models.DestinationLanguage.objects.filter(user=user)  #.values('destLanguage')[0]['destLanguage']

    #  Delete below ///////////////////////////////////
    if destLanguage:
        pass
    else:
        translate_models.DestinationLanguage.objects.create(
            destLanguage='EN',
            user=request.user
        )
    #  Delete above ///////////////////////////////////

    instance = get_object_or_404(translate_models.DestinationLanguage, user=pk)
    if request.method == 'POST':
        user_form = UserUpdateForm(request.POST, instance=request.user)
        language_form = translate_forms.DestinationLanguageForm(request.POST, instance=instance)
        if user_form.is_valid() and language_form.is_valid():
            user_form.save()
            language_form.save()
            messages.success(request, f'Your account has been updated!')
            return redirect('contentlist')

    else:
        user_form = UserUpdateForm(request.POST, instance=request.user)
        language_form = translate_forms.DestinationLanguageForm(request.POST, instance=instance)

    context = {
        'user_form': user_form,
        'language_form': language_form,
        'destLanguage': destLanguage
    }

    return render(request, 'personal/user_profile.html', context)




def user_logout(request):
    logout(request)
    return render(request, 'personal/base.html', {})

mysite/personal/templates/personal/base.html
<!doctype html>

<html>
  <head>
	<title>Puckos</title>
	<meta charset="utf-8" />
	{% load staticfiles %}
	<link rel="stylesheet" href="{% static 'translate/css/translate.css' %}" type = "text/css"/>
	<link rel="stylesheet" href="{% static 'personal/css/base.css' %}" type="text/css">
	<link rel="stylesheet" href="{% static 'personal/css/index.css' %}" type="text/css">
	<link rel="stylesheet" href="{% static 'translate/css/timer.css' %}" type="text/css">
	<link rel="stylesheet" href="{% static 'translate/css/list_content.css' %}" type="text/css">
	<link rel="stylesheet" href="{% static 'translate/css/create_content.css' %}" type="text/css">
	<link rel="stylesheet" href="{% static 'translate/css/delete_content.css' %}" type="text/css">
	<link rel="stylesheet" href="{% static 'personal/css/user_login.css' %}" type="text/css">
	<link rel="stylesheet" href="{% static 'dashboard/css/chart.css' %}" type="text/css">
	<link rel="stylesheet" href="{% static 'dashboard/css/dashboard.css' %}" type="text/css">
	<link rel="stylesheet" href="https://use.fontawesome.com/releases/v5.7.0/css/all.css" integrity="sha384-lZN37f5QGtY3VHgisS14W3ExzMWZxybE1SJSEsQp9S+oqd12jhcu+A56Ebc1zFSJ" crossorigin="anonymous">
  </head>

  <body class="fade-in">
    <!--<div id="main-content-section">-->
		<div class="header-menu">
		  <ul>
			{% if user.is_authenticated %}
			  <li><a href='/logout'>Logout <i class="fas fa-sign-out-alt"></i></a></li>
			  <li><a id="username" href="{% url 'profile' user.id %}">{{ user }} <i class="far fa-address-card"></i></a></li>
			{% endif %}
			  <li><a href='/index'><i class="fas fa-home"></i></a></li>
		  </ul>
		</div>

		<div id="block-content-wrapper">
		{% block content %}
		{% endblock %}
		</div>
		{% include 'dashboard/js.html' %}
		{% include 'dashboard/main_dash_js.html' %}
		{% include 'dashboard/sub_dash_js.html' %}
    <!--</div>-->


    {% block javascript %}{% endblock %}
  </body>
</html>

mysite/personal/templates/personal/header.html
<!DOCTYPE html>
<html lang="en">

<head>
	<title>Puckos</title>
	<meta charset="utf-8" />
	{% load staticfiles %}
	<link rel="stylesheet" href="{% static 'personal/css/bootstrap.min.css' %}" type = "text/css"/>
	<link rel="stylesheet" href="{% static 'translate/css/translate.css' %}" type = "text/css"/>
	<meta name="viewport" content = "width=device-width, initial-scale=1.0">

	<style type="text/css">
		html,
		body {
		  height:100%
		}
	</style>
</head>

<body class="body" style="background-color:#f6f6f6">


		<div class="row">
		  <div class="col-sm-2">
		  <br>

		  <br>
		   <!-- Great, til you resize. -->
			<!--<div class="well bs-sidebar affix" id="sidebar" style="background-color:#fff">-->
			<div class="well bs-sidebar" id="sidebar" style="background-color:#fff">
			  <ul class="nav nav-pills nav-stacked">
				<li><a href='/'>Home</a></li>
				<li><a href='/contentlist'>Available Content</a></li>
				<li><a href='/translator'>Translate</a></li>
				<li><a href='/timer/'>Counter</a></li>
			  </ul>
			</div> <!--well bs-sidebar affix-->
		  </div> <!--col-sm-2-->
		  <div class="col-sm-10">
			<div class='container-fluid'>
			<br><br>
			   {% load crispy_forms_tags %}
			   {% block content %}

			   {% endblock %}
			</div>
		  </div>
		</div>
	</div>
	<footer>
		<div class="container-fluid" style='margin-left:15px'>
			<p><a href="#" target="blank">Contact</a> | <a href="#" target="blank">LinkedIn</a> | <a href="#" target="blank">Twitter</a> | <a href="#" target="blank">Google+</a></p>
		</div>
	</footer>
  <script src="https://code.jquery.com/jquery-3.1.0.min.js"></script>
  {% block javascript %}{% endblock %}
</body>

</html>

mysite/personal/templates/personal/index.html
{% extends "personal/base.html"%}
  {% block javascript %}

    <script>
      var text2 = "I am Puckos",
          text3 = "Send me donuts";
      $(document).on('click', ".menu-item", function(event){
        event.preventDefault();

        $('.app-link').remove();
        $('.content-window-wrapper').text("");
        $(this).removeClass('menu-item');
        $(this).addClass('menu-item-clicked');

        $('.menu-item').toggleClass('spin');

        var linkUrl = $(this).attr('href');
        setTimeout(function(url) { window.location = url; }, 1000, linkUrl);

        var contentid = $(this).attr("id")
        if (contentid == "1") {
          $('.content-window-wrapper').append('<a class="app-link" href="/contentlist"><span>Translator</span></a>');
          $('.content-window-wrapper').append('<a class="app-link" href="/dashboard/"><span>Dashboard</span></a>');
        }
        else if (contentid == "2") {
          $('.content-window-wrapper').text(text2);
        }
        else {
          $('.content-window-wrapper').text(text3);
        }

        $('.content-window-wrapper').animate({
			opacity: 1}, 2500);
      });

      $(document).on('click', ".menu-item-clicked", function(event){
        event.preventDefault();
        $(this).removeClass('menu-item-clicked');

        $('.menu-item').toggleClass('spin');

        $(this).addClass('menu-item');
        $('.content-window-wrapper').animate({opacity: 0}, 1000);


      });



    </script>

  {% endblock %}

  {% block content %}
    <div class="index-wrapper">
      <div class="index-menu-wrapper">
        <div class="menu-item-wrapper left">
          <a href='#' id="1" class="menu-item"><span>Projects</span></a>
        </div>
        <div class="menu-item-wrapper middle">
          <a href='#' id="2" class="menu-item"><span>About Me</span></a>
        </div>
        <div class="menu-item-wrapper right">
          <a href='#' id="3" class="menu-item"><span>Contact</span></a>
        </div>
      </div>
      <div class="content-window-wrapper"></div>
    </div>













  {% endblock %}

mysite/personal/templates/personal/timer.html
{% extends "personal/base.html"%}
		{% block javascript %}
			<script>
			// Set the date we're counting down to
			var countDownDate = new Date("Jan 5, 2019 15:37:25").getTime();

			// Update the count down every 1 second
			var x = setInterval(function() {

			  // Get todays date and time
			  var now = new Date().getTime();

			  // Find the distance between now and the count down date
			  var distance = countDownDate - now;

			  // Time calculations for days, hours, minutes and seconds
			  //var months = Math.floor(distance / (1000 * 60 * 60 * 24 * 30));
			  var days = Math.floor(distance / (1000 * 60 * 60 * 24));
			  var hours = Math.floor((distance % (1000 * 60 * 60 * 24)) / (1000 * 60 * 60));
			  var minutes = Math.floor((distance % (1000 * 60 * 60)) / (1000 * 60));
			  var seconds = Math.floor((distance % (1000 * 60)) / 1000);

			  // Display the result in the element with id="timerp"
			  document.getElementById("timerp").innerHTML = days + "d " + hours + "h "
			  + minutes + "m " + seconds + "s ";

			  // If the count down is finished, write some text
			  if (distance < 0) {
				clearInterval(x);
				document.getElementById("timerp").innerHTML = "EXPIRED";
			  }
			}, 1000);


			function myFunction() {
				var x = document.getElementById("container");
				if (x.style.display === "none") {
					x.style.display = "block";
			  } else {
				x.style.display = "none";
				}
			}




			var y = setInterval(function () {
				var wDayDate = new Date("Jan 30, 2019 09:00:00").getTime();
				//var wDayDate = "IDK"
				if (wDayDate === "IDK") {
					document.getElementById("wDayTimerp").innerHTML = "We don't know yet :("
				}
				else {
			  var now = new Date().getTime();

			  // Find the distance between now and the count down date
			  var distance = wDayDate - now;

			  // Time calculations for days, hours, minutes and seconds
			  //var months = Math.floor(distance / (1000 * 60 * 60 * 24 * 30));
			  var days = Math.floor(distance / (1000 * 60 * 60 * 24));
			  var hours = Math.floor((distance % (1000 * 60 * 60 * 24)) / (1000 * 60 * 60));
			  var minutes = Math.floor((distance % (1000 * 60 * 60)) / (1000 * 60));
			  var seconds = Math.floor((distance % (1000 * 60)) / 1000);
					document.getElementById("wDayTimerp").innerHTML = days + "d " + hours + "h "
			  + minutes + "m " + seconds + "s "
				}
			}
			)

			$('#timerp').on('mouseover', function() {
			  var boxId = $(this).attr('id');
			  $('#'+boxId).fadeOut(400).fadeIn(400);
			});

			$('#wDayTimerp').on('mouseover', function() {
			  $('#wDayTimerp').fadeOut(400).fadeIn(400);
			});




$('.get-request-test').on('click', function() {
        var wordtocheck = $(this).text();
        $.ajax({
            type: 'GET',
            url: 'wordclass/',
            data: {
                'wordtocheck': wordtocheck
            },
            success: function(data){
                if (data.wordexists) {
            alert("***"+wordtocheck+"***"+" exists in the DB "+data.wordrecord);
          }
                else {
            alert("***"+wordtocheck+"***"+" missing")
                }
            }
        })
    });

</script>
{% endblock %}


{% block content %}


	<div id="containerTimer">
		<div id="get-request-test-grid">
			<div class="get-request-test">hur</div>
			<div class="get-request-test-output"></div>
			<div class="get-request-test">atombomb</div>
			<div class="get-request-test-output"></div>
			<div class="get-request-test">tillbaka</div>
			<div class="get-request-test-output"></div>
		</div>
		<p class="timer-box" id="timerp"></p>
		<p class="timer-box" id="wDayTimerp"></p>
	</div>

{% endblock %}

mysite/personal/templates/personal/user_login.html
{% extends "personal/base.html"%}
{% load crispy_forms_tags %}

{% block javascript %}
<script>

</script>
{% endblock %}


{% block content %}
    <div id="login-main">
      <form method="POST" id="login-form">
        {% csrf_token %}
        <fieldset id="login-fieldset">
          {{ form|crispy }}
        </fieldset>
        <div class="create-user-button-container">
          <button class="create-user-button" type="submit"><a>Login</a></button>
          <button class="create-user-button"><a href="{% url 'contentlist' %}">Cancel</a></button>
          <button class="create-user-button" type="submit"><a href='/register'>Register</a></button>
        </div>
      </form>
    </div>
{% endblock %}

mysite/personal/templates/personal/user_profile.html
{% extends "personal/base.html"%}
{% load crispy_forms_tags %}

{% block javascript %}

  <script>

  </script>

{% endblock %}


{% block content %}
    <div id="login-main">

        <form method="POST" id="login-form">
          {% csrf_token %}
          <fieldset id="login-fieldset">
            <div class="current-email">Your current e-mail address is "{{ user.email }}"</div>
              {{ user_form|crispy }}

              {% for language in destLanguage %}
            <div class="current-destlanguage">Your current destination language is "{{ language.destLanguage }}"</div>
              {% endfor %}

              {{ language_form|crispy }}
          </fieldset>
          <div class="create-user-button-container">
            <button class="create-user-button" type="submit"><span>Update</span></button>
            <button class="create-user-cancel create-user-button" href="{% url 'contentlist' %}"><span>Cancel</span></button>
          </div>
        </form>

    </div>
{% endblock %}

mysite/personal/templates/personal/user_register.html
{% extends "personal/base.html"%}
{% load crispy_forms_tags %}

{% block javascript %}

  <script>
$(document).ready(function(){
      $("#id_username").val("");
      $("#id_email").val("");
      $("#id_email2").val("");
      $("#id_password").val("");
    })
  </script>

{% endblock %}


{% block content %}
    <div id="login-main">
      <form method="POST" id="login-form">
        {% csrf_token %}
        <fieldset id="login-fieldset">
          {{ form|crispy }}
        </fieldset>
        <div class="create-user-button-container">
          <button class="create-user-button" type="submit">Register</button>
          <button class="create-user-button"><a href="{% url 'contentlist' %}">Cancel</a></button>
        </div>
      </form>
    </div>
{% endblock %}